### ISSUE TITLE
Rendered ads have a off-by-one image/content association

### ISSUE THREAD

**Issue by mcomisso** [hiddevdploeg/Billboard#36]
Hi, I noticed that the images associated to a banner have the tendency to fall behind after the 1st rendering. 

The first ad works well, then there is a tab switch and coming back to the previous page starts having the mentioned issue.
Example:

<img width="447" alt="Screenshot 2024-04-20 at 12 26 26" src="https://github.com/hiddevdploeg/Billboard/assets/671364/fd9f0317-2066-4e7f-9b08-c380ea24676d">

<img width="445" alt="Screenshot 2024-04-20 at 12 26 52" src="https://github.com/hiddevdploeg/Billboard/assets/671364/9e2c1292-e829-468b-a8c5-80a74353b1d0">

<img width="446" alt="Screenshot 2024-04-20 at 12 27 28" src="https://github.com/hiddevdploeg/Billboard/assets/671364/a90ba662-93c9-47ba-a420-5a5a891ec10f">

The difference between displayed ad and image never increases more than 1 from my tests. 
Tapping on them loads the advert for the title/subtitle displayed.

**Comment by DandyLyons** [comment]
![IMG_5279](https://github.com/hiddevdploeg/Billboard/assets/72824209/dd866647-2a4b-425a-a6c1-56c984275b1d)

I believe this is fixed now and should be closable.

**Comment by mcomisso** [comment]
No, it is still happening.

To see the issue, add a floating banner on a tab, switch to another tab of the app and come back to the first one.

The image stays the same, but the rest of the banner's metadata changes correctly

**Comment by hiddevdploeg** [comment]
Fix is coming later this week :)

**Comment by hiddevdploeg** [comment]
This should be fixed now
